-- 코드를 입력하세요
SELECT *
FROM (
SELECT BOARD_ID, WRITER_ID, TITLE, PRICE, '판매중' AS STATUS
FROM USED_GOODS_BOARD
WHERE CREATED_DATE = '2022-10-05'
AND STATUS = 'SALE'
UNION
SELECT BOARD_ID, WRITER_ID, TITLE, PRICE, '예약중' AS STATUS
FROM USED_GOODS_BOARD
WHERE CREATED_DATE = '2022-10-05'
AND STATUS = 'RESERVED'
UNION
SELECT BOARD_ID, WRITER_ID, TITLE, PRICE, '거래완료' AS STATUS
FROM USED_GOODS_BOARD
WHERE CREATED_DATE = '2022-10-05'
AND STATUS = 'DONE'
) S ORDER BY BOARD_ID DESC